app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::post('oauth/access_token',function(){
    return Response::json(Authorizer::issueAccessToken());
});
Route::post('oauth/facebook',function(){
    return Response::json(Authorizer::issueAccessToken());
});



Route::get('/', function () {
    $events = \App\Event::all()->get(25);
    $categories = \App\Category::get();
    return view('site.home',compact('events','categories'));
});



Route::resource('events','SiteEventController');
Route::get('events/category/{slug}','SiteEventController@index')->name('events.category');

Route::auth();
Route::get('/home', function(){return view('layouts.site');});

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
    Route::get('/',function(){return view('home');});
    Route::resource('managers','ManagerController');
    Route::resource('events','EventController');
    Route::resource('categories','CategoryController');
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');
});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $table = 'events';

    function activities(){
        return $this->hasMany(EventActivity::class,'event_id');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Event;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Event::orderBy('id','DESC')->paginate(5);
        return view('events.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);
        try {
            DB::beginTransaction();

            $input = $request->all();

            $event = Event::create($input);

            $event->save();
            DB::commit();
        }catch (Exception $e){
            DB::rollback();
        }

        return redirect()->route('admin.events.index')
            ->with('success','Event created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Event::find($id);
        return view('events.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Manager::find($id);

        return view('users.edit',compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $input = $request->all();

        $event = Manager::find($id);
        $event->update($input);

        return redirect()->route('admin.events.index')
            ->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Event::find($id)->delete();
        return redirect()->route('admin.events.index')
            ->with('success','Event deleted successfully');
    }
}

resources/views/events/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>@Lang('label.event-new')</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('admin.managers.index') }}"> Back</a>
                    </div>
                </div>
            </div>
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Lang('label.event')
                </div>
                <div class="panel-body">
                    {!! Form::open(array('route' => 'admin.managers.store','method'=>'POST')) !!}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>@Lang('label.name-field'):</strong>
                                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col col-xs-12">
                            <div class="form-group">
                                <strong>Banner</strong>
                                {!! Form::file('image') !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>@Lang('label.description-field'):</strong>
                                {!! Form::text('description', null, array('placeholder' => 'Breve descrição do evento','class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                          <div class="form-group">
                            <strong>@Lang('label.initial-date-field'):</strong>
                            {!! Form::date('initial_date',null,array('placeholder'=>'dd/mm/aaaa','class'=>'form-control datepicker'))!!}
                          </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                          <div class="form-group">
                            <strong>@Lang('label.final-date-field'):</strong>
                            {!! Form::date('final_date',null,array('placeholder'=>'dd/mm/aaaa','class'=>'form-control datepicker'))!!}
                          </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Conteudo</strong>
                                {!! Form::textArea('content', null, array('placeholder' => 'Email','class' => 'form-control text-editor')) !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>@Lang('label.event-new')</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('admin.managers.index') }}"> Back</a>
                    </div>
                </div>
            </div>
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Lang('label.event')
                </div>
                <div class="panel-body">
                    {!! Form::model($event,['route' => 'admin.managers.store','method'=>'POST']) !!}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>@Lang('label.name-field'):</strong>
                                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col col-xs-12">
                            <div class="form-group">
                                <strong>Banner</strong>
                                {!! Form::file('image') !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>@Lang('label.description-field'):</strong>
                                {!! Form::text('description', null, array('placeholder' => 'Breve descrição do evento','class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                          <div class="form-group">
                            <strong>@Lang('label.initial-date-field'):</strong>
                            {!! Form::date('initial_date',null,array('placeholder'=>'dd/mm/aaaa','class'=>'form-control datepicker'))!!}
                          </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                          <div class="form-group">
                            <strong>@Lang('label.final-date-field'):</strong>
                            {!! Form::date('final_date',null,array('placeholder'=>'dd/mm/aaaa','class'=>'form-control datepicker'))!!}
                          </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Conteudo</strong>
                                {!! Form::textArea('content', null, array('placeholder' => 'Email','class' => 'form-control text-editor')) !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>@lang('label.event-list')</h2>
                    </div>
                    <div class="pull-right">
                        @permission('manager-create')
                        <a class="btn btn-success" href="{{ route('admin.events.create') }}"><i class="fa fa-plus"></i> @Lang('label.event-new')</a>
                        @endpermission
                    </div>
                </div>
            </div>
            @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Lang('label.events')
                </div>
                <div class="panel-body" style="padding: 0px">
                    <table class="table table-bordered">
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th width="280px">Action</th>
                        </tr>
                        @foreach ($data as $key => $event)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $event->name }}</td>
                            <td>
                                <a class="btn btn-xs btn-info" href="{{ route('admin.events.show',$event->id) }}">Show</a>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.events.edit',$event->id) }}">Edit</a>
                                {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $event->id],'style'=>'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
            {!! $data->render() !!}
        </div>
    </div>
</div>
@endsection

resources/views/events/show.blade.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: dolal
 * Date: 16/05/2017
 * Time: 21:27
 */