app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::post('oauth/access_token',function(){
    return Response::json(Authorizer::issueAccessToken());
});
Route::post('oauth/facebook',function(){
    return Response::json(Authorizer::issueAccessToken());
});



Route::get('/', function () {
    $events = \App\Event::all()->get(25);
    $categories = \App\Category::get();
    return view('site.home',compact('events','categories'));
});



Route::resource('events','SiteEventController');
Route::get('events/category/{slug}','SiteEventController@index')->name('events.category');

Route::auth();
Route::get('/home', function(){return view('layouts.site');});

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
    Route::get('/',function(){return view('home');});
    Route::resource('managers','ManagerController');
    Route::resource('events','EventController');
    Route::resource('categories','CategoryController');
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Entity
{
    protected $table = 'categories';

    protected $fillable = ['name','slug', 'parent_id'];

    public function parent(){
      return $this->hasOne(Category::class,'parent_id');
    }

    public function childrens(){
      return $this->hasMany(Category::class,'categories','parent_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Category;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
      $data = Category::orderBy('id','DESC')->paginate(5);
      return view('categories.index',compact('data'))
          ->with('i', ($request->input('page', 1) - 1) * 5);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      $categories = Category::lists('name','id');
      return view('categories.create',compact('categories'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $this->validate($request, [
          'name' => 'required',
          'slug' => 'required',
      ]);
      try {
          DB::beginTransaction();

          $input = $request->all();
          $category = Category::create($input);
          $category->save();
          DB::commit();
      }catch (Exception $e){
          DB::rollback();
      }

      return redirect()->route('admin.categories.index')
          ->with('success','Category created successfully');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      $category = Category::with('parent')->find($id);
      return view('categories.show',compact('category'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      $category = Category::find($id);
      $categories = Category::lists('name','id');


      return view('categories.edit',compact('category','categories'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
      $this->validate($request, [
          'name' => 'required',
          'slug' => 'required',
      ]);

      $input = $request->all();


      $category = Category::find($id);
      $category->update($input);
      $category->save();

      return redirect()->route('categories.index')
          ->with('success','Category updated successfully');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      Category::find($id)->delete();
      return redirect()->route('categories.index')
          ->with('success','Category deleted successfully');
  }
}

resources/views/categories/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <h2>@Lang('label.create') @Lang('label.category-new')</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('admin.categories.index') }}"> @Lang('label.back')</a>
                        </div>
                    </div>
                </div>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Regras
                    </div>
                    <div class="panel-body">
                        {!! Form::open(array('route' => 'admin.categories.store','method'=>'POST')) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Nome','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <strong>Slug:</strong>
                                    {!! Form::text('slug', null, array('placeholder' => 'slug','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <strong>Categoria Pai:</strong>
                                    <br/>

                                    {!! Form::select('parent_id', $categories,[], array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Lang('label.save')</button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <h2>Edit Role</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('admin.categories.index') }}"> Back</a>
                        </div>
                    </div>
                </div>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Editar Regras
                    </div>
                    <div class="panel-body">
                        {!! Form::model($category, ['method' => 'PATCH','route' => ['admin.categories.update', $category->id]]) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Nome','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>slug:</strong>
                                    {!! Form::text('slug', null, array('placeholder' => 'Slug','class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Categoria Pai:</strong>
                                    {!! Form::select('parent_id', $categories,null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Salvar</button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <h2>@Lang('label.category-list')</h2>
                        </div>
                        <div class="pull-right">
                            @permission('category-create')
                            <a class="btn btn-success" href="{{ route('admin.categories.create') }}"><i class="fa fa-plus"></i> @Lang('label.category-new')</a>
                            @endpermission
                        </div>
                    </div>
                </div>
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @Lang('label.categories')
                    </div>
                    <div class="panel-body" style="padding: 0px">
                        <table class="table table-bordered">
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th width="280px">Action</th>
                            </tr>
                            @foreach ($data as $key => $category)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->slug }}</td>
                                    <td>

                                        <a class="btn btn-xs btn-info" href="{{ route('admin.categories.show',$category->id) }}">Show</a>
                                        @permission('category-edit')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.categories.edit',$category->id) }}">Edit</a>
                                        @endpermission
                                        @permission('category-delete')
                                        {!! Form::open(['method' => 'DELETE','route' => ['admin.categories.destroy', $category->id],'style'=>'display:inline']) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
                                        {!! Form::close() !!}
                                        @endpermission

                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
                {!! $data->render() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <h2> Show Category</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('admin.categories.index') }}"> Back</a>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Regra
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {{ $category->name }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>slug:</strong>
                                    {{ $category->slug }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Categoria Pai:</strong>
                                    {{ $category->parent_id }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection